### ISSUE TITLE
Unbreakable walls make Boobeam Trap impossible

### ISSUE THREAD

**Issue by AstroTibs** [squid-man/MegaMan2Randomizer2#174]
A couple of times, I've gotten a seed where the wall obstacles can't be broken by any weapon.
This is only a little annoying, but in this particular case, Boobeam is vulnerable only to Air Man's weapon, meaning the turret in the bottom-right can't be hit, making the seed impossible.

Setting-seed is `FZQKQIWEFSAUEM (84789631690087653887)`. I'm using release 0.6.6.4186, but I've had issues from 0.6.3 as well.

**Comment by TheRealQuantam** [comment]
I just checked that seed on that build. What's going on here is that the walls are vulnerable to Bubble Lead. For a while it's been known that Bubble Lead and Crash walls don't get along well, and this is particularly severe in the tight areas in the Boobeam fight; in some spots in the fight it can be very hard to get the Bubble to hit the walls. #219 adds an option to prevent Crash walls from being weak to Bubble to fix this problem.
