### ISSUE TITLE
Option to exit current stage and/or revisit stages

### ISSUE THREAD

**Issue by dagit** [squid-man/MegaMan2Randomizer2#20]
An option to exit a stage might make it easier to avoid softlocks or difficult situations and provide an alternative to resetting when you get crash 3rd.

Being able to revisit stages might be nice if you find metal early and want to farm etanks.

**Comment by TheRealQuantam** [comment]
Upcoming self-destruct provides a solution to this. Waiting on #194.

**Comment by TheRealQuantam** [comment]
Implemented via self-destruct in #238
