### ISSUE TITLE
Add "Bad Scizzors Day" Cutman sprite as playable option

### ISSUE THREAD

**Issue by dagit** [squid-man/MegaMan2Randomizer2#22]

**Comment by dagit** [comment]
There may be a bunch of other romhack sprites that we could add.

**Comment by Bobdedbuilder** [comment]
Well it would be even better if there was an option given within the parameters "upload" your own custom Megaman sprite to control. If anything I have done a lot of work for Stream Avatars. I'm sure it would be something similar in regards to putting the sprites in the appropriate columns and rows and give it the dimensions.

**Comment by TheRealQuantam** [comment]
Isn't this already done?
