### ISSUE TITLE
The wrong stages are shown as being cleared on stage select

### ISSUE THREAD

**Issue by ScrapzGITHUB** [squid-man/MegaMan2Randomizer2#227]
Seed: 71220616055977104532
Hash: NHQBARJDKVPWC
Version: 0.6.7.31240
I've included a zip file that contains the xml with the settings I used as well if you need that.
[settings.zip](https://github.com/user-attachments/files/17807454/settings.zip)

**Comment by TheRealQuantam** [comment]
I was able to start all 8 stages using the settings and seed provided. Was there more specific conditions?

**Comment by ScrapzGITHUB** [comment]
I had two robot masters left and the emulator I was using is FCEUX 2.6.5 I was also using a few savestates and was playing on easy mode.

**Comment by ScrapzGITHUB** [comment]
Oh wait I figured out the problem, the question marks on the stages were displaying over stages already cleared and ones that appeared to be cleared were actually uncleared.

**Comment by TheRealQuantam** [comment]
Okay, I see that it's happening.

**Comment by TheRealQuantam** [comment]
Bizarre. It's triggered by disabling Randomize In Game Text, which SHOULD have no impact on gameplay randomization. Specifically this option (at least in this case) makes the stages where you get the weapons you have in vanilla show as defeated, when the stages you actually got the weapons from in MM2R are the ones that are actually defeated.

Now to figure out why.

**Comment by TheRealQuantam** [comment]
Looks like a pretty simple and easy to fix bug. Though it was hiding another bug: when random letters aren't used for weapons, it uses the letter from the stage the weapon came from, not the weapon itself.
