### ISSUE TITLE
Option for the ability to menu when mega man has sprites on the screen

### ISSUE THREAD

**Issue by dagit** [squid-man/MegaMan2Randomizer2#38]

**Comment by TheRealQuantam** [comment]
Experimental implementation of this for testing to see if it's really that easy or a more elaborate solution is required: https://cdn.discordapp.com/attachments/528035919874359305/1107561265129336932/Mega_Man_2_USA_Experimental_Pause_Patch.ips

**Comment by TheRealQuantam** [comment]
Fixed. Should be closed. @squid-man
