### ISSUE TITLE
Mechanism for loading tournament presets

### ISSUE THREAD

**Issue by dagit** [squid-man/MegaMan2Randomizer2#4]
I'm imagining that a first pass at this could be as simple as loading a json/xml/toml/etc file. We'd just manually hand these out and ask people to put them in the same directory as the randomizer and it would check for it. Maybe named `tournament-20XX.config` and then in the menu of the randomizer there would be a drop down to select the tournament presets.

**Comment by dagit** [comment]
My current leaning on this is to use this json parser: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to

I think we could add a button to the UI "make preset" that just takes the current settings and writes them out. Then the file can be distributed. So that way, the no one has to manually edit the json file and the exact format becomes immaterial to the user.

**Comment by dagit** [comment]
@squid-man I'm assigning this to you because I think you have a better idea of how to add XML resources to the code base.

**Comment by dagit** [comment]
See also #86 and #49

**Comment by CharlieboyX** [comment]
I believe we implemented this with the addition of tournament mode #148
