### ISSUE TITLE
title screen glitch when mega man teleports

### ISSUE THREAD

**Issue by bunder2015** [squid-man/MegaMan2Randomizer2#71]
probably old, but reporting for later troubleshooting...  the N glitches out when starting the game or letting the intro loop.  also the 2 looks a bit messed up.

![MM2-RNG-HORNED (HORNED)_000](https://user-images.githubusercontent.com/12985665/107177321-937b9b00-699f-11eb-8458-c641eac44afb.png)

**Comment by TheRealQuantam** [comment]
Fixed by #134. Should be closed. @squid-man
